### ISSUE TITLE
Simultaneous ETH transactions on server fail

### ISSUE THREAD

**Issue by karzak** [Kava-Labs/switch-api#10]
Expected behavior: payment channels are successfully closed when calling withdraw on ETH uplink.

Actual behavior: Sometimes the peer fails to claim channel. This seems to occur when the ETH server plugin is sending multiple transactions related to separate accounts.

Example output:
```
0|ilp-connector  |   connector:ilp-plugin-ethereum[eth]:debug Attempting to claim channel 0x0e5c9c40383faa05a0bf0d6eb260387db93c80cb59b017e9418b219dbb311b93 for 0 eth +7s
0|ilp-connector  |   connector:ilp-plugin-ethereum[eth]:error Failed to claim channel: Returned error: Transaction gas price is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce. +0ms
0|ilp-connector  |   connector:ilp-plugin-ethereum[eth]:debug btp packet not accepted TypeError: Cannot read property 'message' of undefined
0|ilp-connector  |     at claimIfProfitable.catch.err (/Users/kjd/Kava-Labs/connector-config/node_modules/ilp-plugin-ethereum/src/account.ts:673:53)
0|ilp-connector  |     at process._tickCallback (internal/process/next_tick.js:68:7) +239ms
```

client output:
```
ilp-plugin-ethereum:debug Error while requesting peer to claim channel: {"code":"F00","name":"NotAcceptedError","triggeredAt":"2019-02-25T22:47:14.151Z","data":"Cannot read property 'message' of undefined","protocolData":[]} 
```

**Comment by kincaidoneil** [comment]
Resolved by interledgerjs/ilp-plugin-ethereum@bd3880d9d7f9d2fa08f063377205b0d01a59e5b4 and Kava-Labs/connector-config#3.
