### ISSUE TITLE
Cannnot create multiple LND uplinks in the same process

### ISSUE THREAD

**Issue by karzak** [Kava-Labs/switch-api#8]
Expected behavior: Users should be able to create multiple LND uplinks with the same credentials.

Actual behavior: Creating a second LND uplink fails due to grpc error.

Script to reproduce:
```
# lnd-uplinks.js
const switchApi = require('../build/')

async function main() {
  const api = await switchApi.connect()

  const lndUplink = await api.add({
    settlerType: switchApi.SettlementEngineType.Lnd,
    hostname: '54.165.221.164',
    macaroon:
      'AgEDbG5kArsBAwoQCg1EH7JxBbqg81n3ccBe0BIBMBoWCgdhZGRyZXNzEgRyZWFkEgV3cml0ZRoTCgRpbmZvEgRyZWFkEgV3cml0ZRoXCghpbnZvaWNlcxIEcmVhZBIFd3JpdGUaFgoHbWVzc2FnZRIEcmVhZBIFd3JpdGUaFwoIb2ZmY2hhaW4SBHJlYWQSBXdyaXRlGhYKB29uY2hhaW4SBHJlYWQSBXdyaXRlGhQKBXBlZXJzEgRyZWFkEgV3cml0ZQAABiCcLRErbiLXmzcPo2c2lHWi9PTFNvrrBbJ5XaHaT7QOBw==',
    tlsCert:
      'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNJVENDQWNpZ0F3SUJBZ0lSQUlkeG0xbGNvd2VEZkg5eERtdWdScVF3Q2dZSUtvWkl6ajBFQXdJd096RWYKTUIwR0ExVUVDaE1XYkc1a0lHRjFkRzluWlc1bGNtRjBaV1FnWTJWeWRERVlNQllHQTFVRUF4TVBhWEF0TVRjeQpMVE14TFRreUxURXhNQjRYRFRFNU1ERXlOVEUzTVRBeE5Wb1hEVEl3TURNeU1URTNNVEF4TlZvd096RWZNQjBHCkExVUVDaE1XYkc1a0lHRjFkRzluWlc1bGNtRjBaV1FnWTJWeWRERVlNQllHQTFVRUF4TVBhWEF0TVRjeUxUTXgKTFRreUxURXhNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVFeHJFVXl1VlhpRHdZdlBiYzJ2NgpHUTNETG1TTGl2NUVVWWtpMDlHdEs4UmliN08yM2JoZTV1RXlReWx1b2c2SVRHTmprVllpMlJCNyt5V0JQM3Z3CmxhT0JyRENCcVRBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekNCaFFZRFZSMFIKQkg0d2ZJSVBhWEF0TVRjeUxUTXhMVGt5TFRFeGdnbHNiMk5oYkdodmMzU0NCSFZ1YVhpQ0NuVnVhWGh3WVdOcgpaWFNIQkg4QUFBR0hFQUFBQUFBQUFBQUFBQUFBQUFBQUFBR0hCS3dmWEF1SEJLd1JBQUdIRVA2QUFBQUFBQUFBCkVPM0gvLzZmS3JDSEVQNkFBQUFBQUFBQUFFSWMvLzZ2MDlXSEJEYWwzYVF3Q2dZSUtvWkl6ajBFQXdJRFJ3QXcKUkFJZ0M0YmFCa01LWWx5Y3NpNGxKY1BpS09kanlPOTgvZG4wZ1ZBaWVyVDJmWVlDSUFVNHQzWXFUc2Y4SUdSNwpTSzNHTU55RGJwYVk3dGlOZ1FlOHQ4UzFtQVNjCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K',
    grpcPort: '10039'
    })

  await api.remove(lndUplink)
  console.log("Removed first uplink")
  const lndUplink2 = await api.add({
    settlerType: switchApi.SettlementEngineType.Lnd,
    hostname: '54.165.221.164',
    macaroon:
      'AgEDbG5kArsBAwoQCg1EH7JxBbqg81n3ccBe0BIBMBoWCgdhZGRyZXNzEgRyZWFkEgV3cml0ZRoTCgRpbmZvEgRyZWFkEgV3cml0ZRoXCghpbnZvaWNlcxIEcmVhZBIFd3JpdGUaFgoHbWVzc2FnZRIEcmVhZBIFd3JpdGUaFwoIb2ZmY2hhaW4SBHJlYWQSBXdyaXRlGhYKB29uY2hhaW4SBHJlYWQSBXdyaXRlGhQKBXBlZXJzEgRyZWFkEgV3cml0ZQAABiCcLRErbiLXmzcPo2c2lHWi9PTFNvrrBbJ5XaHaT7QOBw==',
    tlsCert:
      'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNJVENDQWNpZ0F3SUJBZ0lSQUlkeG0xbGNvd2VEZkg5eERtdWdScVF3Q2dZSUtvWkl6ajBFQXdJd096RWYKTUIwR0ExVUVDaE1XYkc1a0lHRjFkRzluWlc1bGNtRjBaV1FnWTJWeWRERVlNQllHQTFVRUF4TVBhWEF0TVRjeQpMVE14TFRreUxURXhNQjRYRFRFNU1ERXlOVEUzTVRBeE5Wb1hEVEl3TURNeU1URTNNVEF4TlZvd096RWZNQjBHCkExVUVDaE1XYkc1a0lHRjFkRzluWlc1bGNtRjBaV1FnWTJWeWRERVlNQllHQTFVRUF4TVBhWEF0TVRjeUxUTXgKTFRreUxURXhNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVFeHJFVXl1VlhpRHdZdlBiYzJ2NgpHUTNETG1TTGl2NUVVWWtpMDlHdEs4UmliN08yM2JoZTV1RXlReWx1b2c2SVRHTmprVllpMlJCNyt5V0JQM3Z3CmxhT0JyRENCcVRBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekNCaFFZRFZSMFIKQkg0d2ZJSVBhWEF0TVRjeUxUTXhMVGt5TFRFeGdnbHNiMk5oYkdodmMzU0NCSFZ1YVhpQ0NuVnVhWGh3WVdOcgpaWFNIQkg4QUFBR0hFQUFBQUFBQUFBQUFBQUFBQUFBQUFBR0hCS3dmWEF1SEJLd1JBQUdIRVA2QUFBQUFBQUFBCkVPM0gvLzZmS3JDSEVQNkFBQUFBQUFBQUFFSWMvLzZ2MDlXSEJEYWwzYVF3Q2dZSUtvWkl6ajBFQXdJRFJ3QXcKUkFJZ0M0YmFCa01LWWx5Y3NpNGxKY1BpS09kanlPOTgvZG4wZ1ZBaWVyVDJmWVlDSUFVNHQzWXFUc2Y4SUdSNwpTSzNHTU55RGJwYVk3dGlOZ1FlOHQ4UzFtQVNjCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K',
    grpcPort: '10039'
    })

  await api.remove(lndUplink2)
  console.log("Removed second uplink")
  }
  main().then(res => process.exit(0)).catch(e => { console.log(e); process.exit(1) })
```

Output:
```
Removed first uplink
Error: The channel has been closed
    at Immediate.checkState (/Users/kjd/Kava-Labs/switch-api/node_modules/grpc/src/client.js:840:16)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by kincaidoneil** [comment]
@karzak Does 2a589624b6d0936b903d7410c22dcee6d9839859 fix this for you?
